#!/bin/sh

#
# Copyright 2021 HyperDevs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Misc variables
BOLD=$(tput bold)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NO_STYLE=$(tput sgr0)

# Run detekt over our files
echo "${BOLD}Running detekt${NO_STYLE}"

# Stash any unstaged changes, based on https://gist.github.com/KenVanHoeylandt/c7a928426bce83ffab400ab1fd99054a
# and https://stackoverflow.com/questions/13780700/how-can-i-run-git-pre-commit-checks-only-on-staged-content
git diff --full-index --binary --no-color > /tmp/stash.tmp
git stash -q --keep-index

# Verify that detekt succeeded running on the latest staged files
RESULT=0
if GIT_WORK_TREE=".." ./gradlew detekt --daemon; then # Fix for Ubuntu suggested in https://github.com/gladed/gradle-android-git-version/issues/36
  echo "${GREEN}Your code is properly formatted!${NO_STYLE}"
else
  echo "${RED}Your files don't pass detekt, aborting commit...${NO_STYLE}"
  RESULT=1
fi

# Re-apply stashed changes and remove data
if [ -s /tmp/stash.tmp ]; then # Only apply if the patch file has data
  git apply --whitespace=nowarn < /tmp/stash.tmp
fi
git stash drop -q
rm /tmp/stash.tmp

# Propagate result
[ $RESULT -ne 0 ] && exit 1
exit 0
